### ISSUE TITLE
Modularize functions

### ISSUE THREAD

**Issue by megamorf** [Dapacruz/VMware.VimAutomation.Custom#2]
Having each function in its own file improves the git workflow and readability. 

Expect a pull request later today or tomorrow.

**Comment by dapacruz** [comment]
Really nice improvement. I will look it over more thoroughly very soon. Thank you!

**Comment by megamorf** [comment]
Thanks :-) I'd suggest merging #4 first before you merge #5.
Or you skip #4 entirely and only merge #5 since it's based on #4, your choice.
