### ISSUE TITLE
Incorporate Appveyor for automatic PS Gallery publishing

### ISSUE THREAD

**Issue by megamorf** [Dapacruz/VMware.VimAutomation.Custom#3]
Implement a CI approach to easily publish feature updates and bug fixes to the PowerShell gallery.

Expect a pull request today or tomorrow.

**Comment by dapacruz** [comment]
Great idea. I look forward to getting this implemented. Thanks again.

**Comment by megamorf** [comment]
I'm already on it, just need to push it. So hold off until then, ok :-)

**Comment by dapacruz** [comment]
Thanks again for doing this. It is working great! Please feel free to submit more pull requests! I would love the help. Cheers.
